version: '3'

services:

  database:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: root
      MYSQL_DATABASE: pensionator
    ports:
      - '3307:3306'
    restart: always

  appserver:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    depends_on:
      - database
    image: pensionator_app
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://database:3306/pensionator'
    links:
      - database
    ports:
      - '8080:8080'
      - '8000:8000'
    restart: always


